# Only for building testing version by Github CI workflow

name: Android apk CI(armv8-64 only)

on:
  push:
    branches: [ "master" ]
    paths:
      #- 'idTech4Amm/**'
      #- 'Q3E/**'
      - '.github/workflows/android.yml'
      - '.github/workflows/android.changelog'
  pull_request:
    branches: [ "master" ]
    paths:
      #- 'idTech4Amm/**'
      #- 'Q3E/**'
      - '.github/workflows/android.yml'
      - '.github/workflows/android.changelog'

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup jdk 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: gradle

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential # libtinfo5

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        barch=-Pabifilters=arm64-v8a
        # build Xash3d only
        echo "Build Xash3D libraries"
        bargs=$barch -Pcmake_options=-DGAME_DOOM3=OFF,-DGAME_RTCW=OFF,-DGAME_QUAKE3=OFF,-DGAME_QUAKE2=OFF,-DGAME_QUAKE1=OFF,-DGAME_TDM=OFF,-DGAME_DOOM3BFG=OFF,-DGAME_DOOM=OFF,-DGAME_ETW=OFF,-DGAME_REALRTCW=OFF,-DGAME_FTEQW=OFF,-DGAME_JK=OFF,-DGAME_SERIOUSSAM=OFF,-DGAME_REALRTCW=OFF,-DGAME_SOURCE=OFF
        ./gradlew assembleRelease $bargs
        echo "Copy Xash3D libraries to libs"
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libxash3d*so Q3E/libs/arm64-v8a
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libfilesystem_stdio.so Q3E/libs/arm64-v8a
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libcs16_client.so Q3E/libs/arm64-v8a
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libcs16_menu.so Q3E/libs/arm64-v8a
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libcs16_server.so Q3E/libs/arm64-v8a
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libcs16_yapb.so Q3E/libs/arm64-v8a
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libhlsdk_client.so Q3E/libs/arm64-v8a
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libhlsdk_server.so Q3E/libs/arm64-v8a
        ls Q3E/libs/arm64-v8a
        # build Source only
        echo "Clean builds"
        ./gradlew clean $bargs
        echo "Build Source libraries"
        bargs=$barch -Pcmake_options=-DGAME_DOOM3=OFF,-DGAME_RTCW=OFF,-DGAME_QUAKE3=OFF,-DGAME_QUAKE2=OFF,-DGAME_QUAKE1=OFF,-DGAME_TDM=OFF,-DGAME_DOOM3BFG=OFF,-DGAME_DOOM=OFF,-DGAME_ETW=OFF,-DGAME_REALRTCW=OFF,-DGAME_FTEQW=OFF,-DGAME_JK=OFF,-DGAME_SERIOUSSAM=OFF,-DGAME_REALRTCW=OFF,-DGAME_XASH3D=OFF,-DBUILD_SOURCE_HL2=OFF,-DBUILD_SOURCE_HL2MP=OFF,-DBUILD_SOURCE_EPISODIC=OFF,-DBUILD_SOURCE_HL1=OFF,-DBUILD_SOURCE_HL1MP=OFF,-DBUILD_SOURCE_PORTAL=OFF
        ./gradlew assembleRelease $bargs
        echo "Copy Source libraries to libs"
        cp -f Q3E/build/intermediates/library_jni/release/jni/arm64-v8a/libsource*so Q3E/libs/arm64-v8a
        ls Q3E/libs/arm64-v8a
        # build Others
        echo "Clean builds"
        ./gradlew clean $bargs
        echo "Build final apk"
        bargs=$barch -Pcmake_options=-DGAME_XASH3D=OFF,-DGAME_SOURCE=OFF
        ./gradlew assembleRelease $bargs

    - name: Rename APK
      id: rename_apk
      run: |
        apk_file=idTech4A++-testing-`date "+%Y_%m_%d-%H_%M_%S"`.apk
        cp ./idTech4Amm/build/outputs/apk/release/idTech4Amm-release.apk $apk_file
        echo "::set-output name=value::$apk_file"
      working-directory: ${{ github.workspace }}

    - name: Delete tag and release
      uses: dev-drprasad/delete-tag-and-release@v1.1
      with:
        tag_name: android_testing
        delete_release: true
        repo: glKarin/com.n0n3m4.diii4a
        github_token: ${{ secrets.TOKEN }}

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN }}"
        automatic_release_tag: "android_testing"
        prerelease: true
        title: "Android armv8-64 testing (Non-release. Automatic CI builds)"
        files: |
          ${{ steps.rename_apk.outputs.value }}
