name: Android apk CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: .
        
    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Setup jdk 11
      uses: actions/setup-java@v4
      with:
        java-version: 11
        distribution: 'temurin'
        cache: gradle

    - name: Setup build environment
      run: |
        sudo apt-get update
        sudo apt-get -y install build-essential libtinfo5

    - name: Build with Gradle
      run: |
        chmod +x ./gradlew
        ./gradlew assembleRelease

    - name: Rename APK
      id: rename_apk
      run: |
        apk_file=idTech4Amm-test-`date "+%Y_%m_%d-%H_%M_%S"`.apk
        cp ./idTech4Amm/build/outputs/apk/release/idTech4Amm-release.apk $apk_file
        echo $apk_file
      working-directory: ${{ github.workspace }}

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN }}"
        automatic_release_tag: "test"
        prerelease: true
        title: "Testing(Automatic CI builds)"
        files: |
          ${{ steps.rename_apk.outputs.value }}
