# Only for building testing version by Github CI workflow

name: DOOM3 Windows X64 MSVC CI

on:
  push:
    branches: [ "master" ]
    #paths:
      #- 'Q3E/src/main/jni/doom3/neo/**'
  pull_request:
    branches: [ "master" ]
    #paths:
      #- 'Q3E/src/main/jni/doom3/neo/**'

jobs:
  build-doom3-windows-x64-msvc:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang

    defaults:
      run:
        working-directory: .
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.25.2"

    - name: Setup vcpkg
      uses: johnwason/vcpkg-action@v6
      with:
        pkgs: 'SDL2 curl openal-soft zlib'
        triplet: x64-windows
        token: ${{ secrets.TOKEN }}
        github-binarycache: true

    - name: Configure project with CMake
      run: |
        dir .\vcpkg\packages
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake CMakeLists.txt

    - name: Build with Ninja
      run: |
        cmake --build . --config Release

    - name: Package
      run: |
        dir Release
      working-directory: ${{ github.workspace }}
