# Only for building testing version by Github CI workflow

name: DOOM3 Windows X64 MSVC CI

on:
  push:
    branches: [ "master" ]
    #paths:
      #- 'Q3E/src/main/jni/doom3/neo/**'
  pull_request:
    branches: [ "master" ]
    #paths:
      #- 'Q3E/src/main/jni/doom3/neo/**'

jobs:
  build-doom3-windows-x64-msvc:
    runs-on: windows-latest

    strategy:
      fail-fast: false

      matrix:
        os: [windows-latest]
        build_type: [Release]
        c_compiler: [cl]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
        exclude:
          - os: windows-latest
            c_compiler: gcc
          - os: windows-latest
            c_compiler: clang

    defaults:
      run:
        working-directory: .
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install CMake and Ninja
      uses: lukka/get-cmake@latest
      with:
        cmakeVersion: "3.25.2"

    - name: Setup vcpkg and install depends
      uses: johnwason/vcpkg-action@v6
      with:
        pkgs: 'SDL2 curl openal-soft zlib'
        triplet: x64-windows
        token: ${{ secrets.TOKEN }}
        github-binarycache: true

    - name: Configure project with CMake
      run: |
        cmake -DCMAKE_TOOLCHAIN_FILE=${{ github.workspace }}/vcpkg/scripts/buildsystems/vcpkg.cmake CMakeLists.txt

    - name: Build with Ninja
      run: |
        cmake --build . --config Release

    - name: Copy OpenAL32.dll
      run: |
        xcopy /Y/Q ${{ github.workspace }}\vcpkg\packages\openal-soft_x64-windows\bin\OpenAL32.dll Q3E\src\main\jni\doom3\neo\Release\

    - name: Prepare package
      id: prepare_release
      run: |
        dir Q3E\src\main\jni\doom3\neo\Release
        set d=%date%
        set t=%time%
        set now=%d:~0,4%-%d:~5,2%-%d:~8,2%_%t:~0,2%-%t:~3,2%-%t:~6,2%
        set now=%now: =0%
        set zip_file=idTech4A++-test_windows_x64_release-%now%.zip
        echo ::set-output name=value::%apk_file%

    - name: Package
      uses: vimtor/action-zip@v1.2
      with:
        files: Q3E\src\main\jni\doom3\neo\Release\*.dll Q3E\src\main\jni\doom3\neo\Release\Doom3.exe
        dest: ${{ steps.prepare_release.outputs.value }}
        recursive: false

    - name: Create release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.TOKEN }}"
        automatic_release_tag: "windows_x64_testing"
        prerelease: true
        title: "Windows X64 testing (Non-release. Automatic CI builds)"
        files: |
          ${{ steps.prepare_release.outputs.value }}
