# Only for building testing version by Github CI workflow

name: Test

on:
  push:
    branches: [ "master" ]
    paths:
      - 'Q3E/src/main/jni/doom3/neo/**'
      - '.github/workflows/test.yml'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'Q3E/src/main/jni/doom3/neo/**'
      - '.github/workflows/test.yml'

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      # Set fail-fast to false to ensure that feedback is delivered for all matrix combinations. Consider changing this to true when your workflow is stable.
      fail-fast: false

      # To add more build types (Release, Debug, RelWithDebInfo, etc.) customize the build_type list.
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        build_type: [ Release ]
        bits: [ 64, 32 ]
        include:
          - os: windows-latest
            c_compiler: cl
            cpp_compiler: cl
          - os: ubuntu-latest
            c_compiler: gcc # clang
            cpp_compiler: g++ # clang++
        exclude:
          - os: ubuntu-latest
            bits: 32

    defaults:
      run:
        working-directory: .

    steps:
      - name: Set strings
        id: strings
        shell: bash
        run: |
          if [ "x${ ${{ matrix.bits }} }" = "x86" ]; then echo "arch=86" >> "$GITHUB_OUTPUT"; else echo "arch=64" >> "$GITHUB_OUTPUT"; fi

      - name: echo
        run: echo ${{ steps.strings.outputs.arch }} ${{ github.workspace }} ${{ matrix.os }}-${{ matrix.bits }}